const ShopActionTypes = {
    FETCH_SUPPLIES_START: 'FETCH_SUPPLIES_START',
    FETCH_SUPPLIES_SUCCESS: 'FETCH_SUPPLIES_SUCCESS',
    FETCH_SUPPLIES_FAILURE: 'FETCH_SUPPLIES_FAILURE'
};

export default ShopActionTypes;