export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_DELIVERY: 'SET_DELIVERY',
    SET_PAYMENT: 'SET_PAYMENT',
    SET_USER_INPUT: 'SET_USER_INPUT',
    ADD_EXISTING_USER: 'ADD_EXISTING_USER'
}

export default UserActionTypes;